import 'tailwindcss/tailwind.css';
import { Inter } from "next/font/google";  // Import Inter font with Latin subset
import '../../public/swiper-bundle.min.css';
import "./globals.css";
import axios from "axios";
import { useEffect } from 'react';
import API_BASE_URL from '@/config';
//alert(API_BASE_URL)
//Ensure correct import and usage of Inter font with Latin subset
const inter = "'Inter', sans-serif";  // This assumes Inter is already imported correctly

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {

  useEffect(() => {
    const initializeToken = async () => {
      if (typeof window !== "undefined") {
        const token = localStorage.getItem('username');
        if (!token) {
          try {
            const response = await axios.post(`${API_BASE_URL}/auth/login`, {
              username: 'ganeshku',
              password: '123457'
            });
            const tokenAccess = response.data.access_token;
            localStorage.setItem('username', tokenAccess);
          } catch (error) {
            console.error('Error fetching token:', error);
          }
        }
      }
    };

    initializeToken();
  }, []);  // Run only once on component mount

  return <Component {...pageProps} />;
}

export default MyApp;
