import 'tailwindcss/tailwind.css';
import { Inter } from "next/font/google";
import '../../public/swiper-bundle.min.css';
import "./globals.css";
import axios from "axios";
import { useEffect } from 'react';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





//console.log(token);

if (typeof localStorage !== "undefined") {
  // Safe to use localStorage here
  var token = localStorage.getItem('username');
  if(!token){
        const response = await axios.post("http://localhost:80/auth/login", {
          username:'ganeshku',
          password:'123457'
        });
        var tokenAccess = response.data.access_token;
        localStorage.setItem('username', tokenAccess);
  }
 
} else {
  // Handle the case where localStorage is not available
  console.error("localStorage is not supported");
}



function MyApp({ Component, pageProps }) {
    
    
    return <Component {...pageProps} />;
}
  
export default MyApp;
