import 'tailwindcss/tailwind.css';
import { Inter } from "next/font/google";
import '../../public/swiper-bundle.min.css';
import "./globals.css";
import { useAuth } from '@/utils/useAuth';
import { useRouter } from 'next/router';

const inter = "'Inter', sans-serif";  // This assumes Inter is already imported correctly

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {
  const { loading, token } = useAuth();  // Get loading and token status
  const router = useRouter();

  // If the token is still loading or unavailable, show a loading spinner or screen
  if (loading) {
    return <div>Loading...</div>;
  }

  // Render the app only if the user has the token
  if (!token) {
    router.push('/login');  // Redirect if no token is available
    return null;
  }

  return <Component {...pageProps} />;
}

export default MyApp;
